---
title: "Colony Loss"
author: "Abby Bowen"
format: html
editor: visual
---

```{r}
here::here("data", "colony.csv")
library(gtsummary)
library(readr)
library(dplyr)
colony <- read_csv("data/colony.csv")
View(colony)
```
```{r}
#| label: tbl-months
#| tbl-cap: "Colony Losses and Additions By Month"
tbl_summary(
	colony,
	by = months,
	include = c(colony_lost_pct, colony_added, colony_lost))
```

```{r}
linear_model <- lm(colony_lost_pct ~ months + state + year + colony_added + colony_reno_pct, data = colony)
stats <- list(n = nrow(colony),
              mean_colony = mean(colony$colony_lost, na.rm = TRUE))
```

```{r}
#| label: tbl-regression
#| tbl-cap: "Multivariable Regression Results"
tbl_regression(
	linear_model,
	exponentiate = FALSE,
	label = list(
		months ~ "Months",
		state ~ "State",
		year ~ "Year",
		colony_added ~ "Colony Added",
		colony_reno_pct ~ "Colony Renovated (%)"
	)
)
```

testing `r stats$mean_colony`

```{r}
#| label: fig-hist
#| fig-cap: "Colony Loss Histogram"
hist(colony[["colony_lost_pct"]],
		 main = paste("Histogram of Colony Losses"),
		 xlab = "Percent of Colonies Lost",
		 ylab = "Frequency",
		 col = "pink",
		 border = "black")
```
